<?php
namespace App\Constants;

class Constant{
    const ORDER_STATUS = ['PENDING_CONFIRMATION','PENDING_PAYMENT', 'PAYMENT_CONFIRMED', 'PENDING_DELIVERY', 'DELIVERED', 'COMPLETED' ];
    const PAYMENT_PURPOSE = ['BOOK PURCHASE', 'EVENT BOOKING'];
    const TRANSCATION_STATUS = ['PENDING_CONFIRMATION', 'PAYMENT_CONFIRMED' ];
    const RETREAT_STATUS = ['PENDING', 'APPROVED', 'ACTIVE', 'COMPLETED'];
}